### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQcjgwMUdJaXFpdjBCS3RpT1VyZUliYUJkSnAxU2NoaGs2WlgzNDdUR2ZrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1Mzg3NjU1LCJleHAiOjE2NjU0NzQwNTV9.M4QFAHMmox2db4rpH358-r--aDODpyHTPyBwTOrYkmc

{
  "description" : "상품 설명",
  "items" : [
    {
      "count" : 1,
      "name" : "270",
      "price" : 10000
    }
  ],
  "name" : "나이키 에어포스"
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQcjgwMUdJaXFpdjBCS3RpT1VyZUliYUJkSnAxU2NoaGs2WlgzNDdUR2ZrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1Mzg3NjU1LCJleHAiOjE2NjU0NzQwNTV9.M4QFAHMmox2db4rpH358-r--aDODpyHTPyBwTOrYkmc


{
  "productId" : 1,
  "count" : 1,
  "name" : "280",
  "price" : 10000
}


### 상품 수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQcjgwMUdJaXFpdjBCS3RpT1VyZUliYUJkSnAxU2NoaGs2WlgzNDdUR2ZrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1Mzg3NjU1LCJleHAiOjE2NjU0NzQwNTV9.M4QFAHMmox2db4rpH358-r--aDODpyHTPyBwTOrYkmc

{
  "description" : "상품 설명",
  "items" : [
    {
      "id" : 1,
      "count" : 1,
      "name" : "280",
      "price" : 10000
    }
  ],
  "id" : 1,
  "name" : "나이키 에어포스 한정판"
}

### 상품 아이템 수정
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJQcjgwMUdJaXFpdjBCS3RpT1VyZUliYUJkSnAxU2NoaGs2WlgzNDdUR2ZrPSIsImp0aSI6IkNtWUR2NU1LNVlVeWlrOEtHTkR3b3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNjY1Mzg3NjU1LCJleHAiOjE2NjU0NzQwNTV9.M4QFAHMmox2db4rpH358-r--aDODpyHTPyBwTOrYkmc


{
  "id" : 1,
  "productId" : 1,
  "count" : 1,
  "name" : "260",
  "price" : 10000
}